bcsp.exe depth p_1.txt out1_depth.txt
bcsp.exe depth p_2.txt out2_depth.txt
bcsp.exe depth p_3.txt out3_depth.txt
bcsp.exe depth p_4.txt out4_depth.txt
bcsp.exe depth p_5.txt out5_depth.txt
bcsp.exe depth p_6.txt out6_depth.txt
bcsp.exe depth p_7.txt out7_depth.txt
bcsp.exe depth p_8.txt out8_depth.txt
bcsp.exe depth p_9.txt out9_depth.txt
bcsp.exe depth p_10.txt out10_depth.txt
bcsp.exe hill p_1.txt out1_hill.txt
bcsp.exe hill p_2.txt out2_hill.txt
bcsp.exe hill p_3.txt out3_hill.txt
bcsp.exe hill p_4.txt out4_hill.txt
bcsp.exe hill p_5.txt out5_hill.txt
bcsp.exe hill p_6.txt out6_hill.txt
bcsp.exe hill p_7.txt out7_hill.txt
bcsp.exe hill p_8.txt out8_hill.txt
bcsp.exe hill p_9.txt out9_hill.txt
bcsp.exe hill p_10.txt out10_hill.txt
bcsp.exe hill p_1.txt out11_hill.txt
bcsp.exe hill p_2.txt out12_hill.txt
bcsp.exe hill p_3.txt out13_hill.txt
bcsp.exe hill p_4.txt out14_hill.txt
bcsp.exe hill p_5.txt out15_hill.txt
bcsp.exe hill p_6.txt out16_hill.txt
bcsp.exe hill p_7.txt out17_hill.txt
bcsp.exe hill p_8.txt out18_hill.txt
bcsp.exe hill p_9.txt out19_hill.txt
bcsp.exe hill p_10.txt out20_hill.txt
bcsp.exe hill p_1.txt out21_hill.txt
bcsp.exe hill p_2.txt out22_hill.txt
bcsp.exe hill p_3.txt out23_hill.txt
bcsp.exe hill p_4.txt out24_hill.txt
bcsp.exe hill p_5.txt out25_hill.txt
bcsp.exe hill p_6.txt out26_hill.txt
bcsp.exe hill p_7.txt out27_hill.txt
bcsp.exe hill p_8.txt out28_hill.txt
bcsp.exe hill p_9.txt out29_hill.txt
bcsp.exe hill p_10.txt out30_hill.txt
bcsp.exe hill p_1.txt out31_hill.txt
bcsp.exe hill p_2.txt out32_hill.txt
bcsp.exe hill p_3.txt out33_hill.txt
bcsp.exe hill p_4.txt out34_hill.txt
bcsp.exe hill p_5.txt out35_hill.txt
bcsp.exe hill p_6.txt out36_hill.txt
bcsp.exe hill p_7.txt out37_hill.txt
bcsp.exe hill p_8.txt out38_hill.txt
bcsp.exe hill p_9.txt out39_hill.txt
bcsp.exe hill p_10.txt out40_hill.txt
bcsp.exe hill p_1.txt out41_hill.txt
bcsp.exe hill p_2.txt out42_hill.txt
bcsp.exe hill p_3.txt out43_hill.txt
bcsp.exe hill p_4.txt out44_hill.txt
bcsp.exe hill p_5.txt out45_hill.txt
bcsp.exe hill p_6.txt out46_hill.txt
bcsp.exe hill p_7.txt out47_hill.txt
bcsp.exe hill p_8.txt out48_hill.txt
bcsp.exe hill p_9.txt out49_hill.txt
bcsp.exe hill p_10.txt out50_hill.txt


